name: CI with Dependency Caching

on:
  push:
    branches:
      - main  # Or master, depending on your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # --- 1. Cache Step ---
      - name: prime-cache-c46fbd2
        id: cache-dependencies  # Assign an ID to reference the output
        uses: actions/cache@v4
        with:
          path: ~/.npm  # Example: Change this path based on your project's dependencies (e.g., ~/.npm, ~/.m2, vendor/, etc.)
          key: cache-c46fbd2-${{ hashFiles('package-lock.json') }} # Key includes the fixed name and a hash of a file that changes when dependencies update
          restore-keys: |
            cache-c46fbd2-

      # --- 2. Prime/Dependency Installation Step ---
      - name: Install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm install  # Example: Change this command to your actual dependency installation (e.g., pip install -r requirements.txt, composer install, etc.)
      
      # --- 3. Cache Hit/Miss Echo Step (The requirement) ---
      - name: Echo Cache Result
        run: echo "Cache hit status for cache-c46fbd2: ${{ steps.cache-dependencies.outputs.cache-hit }}"

      # --- 4. Example: Run Tests (Placeholder) ---
      - name: Run Tests
        run: echo "Running tests after setup..."
